# Generated by Django 2.0.4 on 2018-05-17 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(null=True, to='post.Tag'),
        ),
    ]
